### ISSUE TITLE
Please describe basic authentication with proxy server is not supported by SCCM SUP

### ISSUE THREAD

**Issue by yushinok** [MicrosoftDocs/SCCMDocs.ja-jp#24]
Could you please describe basic proxy authentication with proxy server is not supported by SCCM SUP?
Related to this blog article. I would like to make this statement official on this page.
When customer enabled basic authentication on WSUS console, it will be unchecked by WCM.

How Can We Enable Basic Proxy Authentication On The Software Update Points?
https://blogs.technet.microsoft.com/carlossantiago/2008/08/05/how-can-we-enable-basic-proxy-authentication-on-the-software-update-points/

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 926d0167-454c-f8c0-177d-0b1de31b8a77
* Version Independent ID: e1a16df1-da95-3783-c683-cd80fe43bf6d
* Content: [プロキシ サーバーのサポート - Configuration Manager](https://docs.microsoft.com/ja-jp/sccm/core/plan-design/network/proxy-server-support#feedback)
* Content Source: [sccm/core/plan-design/network/proxy-server-support.md](https://github.com/Microsoft/SCCMDocs.ja-jp/blob/live/sccm/core/plan-design/network/proxy-server-support.md)
* Product: **configuration-manager**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
@MicrosoftDocs/mor - are you able to [transfer this issue](https://help.github.com/articles/transferring-an-issue-to-another-repository/) to the main [SCCMDocs repo](https://github.com/MicrosoftDocs/SCCMdocs)? (I'm not an admin on the localized repos to move it.)

**Comment by CeciAc** [comment]
Issue moved to [MicrosoftDocs/SCCMdocs #1059](https://github.com/MicrosoftDocs/SCCMdocs/issues/1059) via [**ZenHub**](https://www.zenhub.com/)

**Comment by CeciAc** [comment]
Hi @aczechowski 
I just migrated the issue to the source repo and closed this one.
Please, follow up this issue here: https://github.com/MicrosoftDocs/SCCMdocs/issues/1059 

Kind regards
Microsoft DOCS International Team
