### ISSUE TITLE
[LOC] "Windows こんにちは" needs to be replaced with "Windows Hello"

### ISSUE THREAD

**Issue by hyoshioka0128** [MicrosoftDocs/SCCMDocs.ja-jp#28]
https://docs.microsoft.com/ja-jp/sccm/mdm/deploy-use/windows-hello-for-business-settings

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 6ecf9e9d-a022-08d3-3992-25571a457779
* Version Independent ID: 15e16864-a9eb-be8f-df57-87c3903ba913
* Content: [Windows Hello for Business の設定 - Configuration Manager](https://docs.microsoft.com/ja-jp/sccm/mdm/deploy-use/windows-hello-for-business-settings)
* Content Source: [sccm/mdm/deploy-use/windows-hello-for-business-settings.md](https://github.com/Microsoft/SCCMDocs.ja-jp/blob/live/sccm/mdm/deploy-use/windows-hello-for-business-settings.md)
* Product: **configuration-manager**
* Technology: **configmgr-hybrid**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by CeciAc** [comment]
Hello, @hyoshioka0128
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.

Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
こんにちは、@hyoshioka0128

フィードバックをお送りいただきありがとうございました。 

Microsoft の言語チームでは、お客様の言語担当者からのご提案を検証し、それを受け入れることになりました。お寄せいただいたフィードバックを実装し、ドキュメント サイト上の次のページの更新された記事に公開しました: https://docs.microsoft.com/ja-jp/sccm/mdm/deploy-use/windows-hello-for-business-settings

記事の品質向上にご協力いただき誠にありがとうございました。引き続きお客様からの貴重なフィードバックをお待ちしています。 

敬具 
Microsoft DOCS International Team
