### ISSUE TITLE
クライアント通知のアクセス許可を持つロール

### ISSUE THREAD

**Issue by K2Relief** [MicrosoftDocs/SCCMDocs.ja-jp#30]
クライアント通知に必要な「リソースの通知」アクセス許可ですが、以下の組み込みセキュリティロールは既定で有効になっているとのことですが、「インフラストラクチャ管理者」は「オペレーション管理者」の誤りではないでしょうか？

・完全な権限を持つ管理者
・インフラストラクチャ管理者

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: fcab1edf-5ca0-4655-8ed4-bbde950e6785
* Version Independent ID: dab40755-ae51-ede3-4f69-912ce0835c6d
* Content: [クライアント通知 - Configuration Manager](https://docs.microsoft.com/ja-jp/configmgr/core/clients/manage/client-notification#feedback)
* Content Source: [sccm/core/clients/manage/client-notification.md](https://github.com/Microsoft/SCCMDocs.ja-jp/blob/live/sccm/core/clients/manage/client-notification.md)
* Product: **configuration-manager**
* Technology: **configmgr-other**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by srvbpigh** [comment]
Hello, @K2Relief
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by aczechowski** [comment]
Thank you @K2Relief for the feedback, I confirmed this is a valid document bug with the article. It should be **Full Administrator** and **Operations Administrator**. I'll fix the bug in the base English content now. It may take a few days for the content to be localized in other languages such as Japanese. Thank you again for pointing out this error.

#please-translate

**Comment by aczechowski** [comment]
Change made with MicrosoftDocs/SCCMDocs-pr#4636
#please-close

**Comment by CeciAc** [comment]
上記のコメントからの翻訳

@K2Relief様、フィードバックをありがとうございます。こちらは、ドキュメントのバグで間違いありません。「完全な管理者」もしくは、「運用管理者」である必要があります。もとになった、英語のコンテンツのバグをすぐに修正いたします。このコンテンツがほかの言語、日本語などにローカライズされるまで、数日かかる可能性がありますことをご了承ください。エラーのご指摘に感謝いたします。
